### ISSUE TITLE
seg fault

### ISSUE THREAD

**Issue by wheaton5** [wtsi-hpag/PretextMap#1]
Hi Ed,

I've run this successfully, but am now running into a segmentation fault.

My command is
samtools view -h hic_chromosomes.bam | PretextMap -o chromosome.pretext --sortby length --sortorder descend --mapq 10

and this file is located at /lustre/scratch118/malaria/team222/hh5/datasets/assembly/ilvanatal1
Let me know if you don't have access.

The chromosome contig names are quite long which may be the problem, idk.

Best,
Haynes

**Comment by wheaton5** [comment]
and a followup is 
Is there a sort order I can get with samtools sort which wouldn't then need further sorting by PretextMap?

**Comment by EdHarry** [comment]
Hi Haynes,

It probably is the long names, but I'll double check...

Pretext only sorts the sequences, not the reads, so is trivially fast

**Comment by EdHarry** [comment]
Hi Haynes,

I've confirmed it's the long sequence names causing the problem. Pretext supports sequence names upto 64 chars.
You can try testing this:
```
samtools view ... | awk '{print gensub(/scaff_([0123456789]+)_contig_tig([0123456789]+)[^\t]+(\s)/,"\\1_\\2\\3","g")}' | PretextMap ...
```
to mangle the names down in size to confirm it works 

Unfortunatly if I change the upper character limit I'll also have to update the viewer to read the longer names.

**Comment by wheaton5** [comment]
That's fine. Thanks for confirming.
